pipeline:
  identifier: Build_jhttp_1698175770824
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: Java_Sample_Project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build test and run
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
